### ISSUE TITLE
Word / Parameter Encoding in URL

### ISSUE THREAD

**Issue by ragingprodigy** [larikraun/slackword#9]
Try using `urlencode(String $url)` to encode your query string rather than `str_replace`. This would also handle other special characters, I guess

**Comment by shalvah** [comment]
Or maybe `http_build_query($query)` ... This saved my skin some days back.
😄

**Comment by ragingprodigy** [comment]
That (`http_build_query`) is even better.

**Comment by shalvah** [comment]
Turns out you didn't use the `getUrl` function though. I think you should add this line in your `WordRequest::getDefinition($word)` , before actually making the request
```
urlencode($word) //or http_build_query($word)
```
As @ragingprodigy mentioned, this will encode all special characters appropriately.

**Comment by larikraun** [comment]
Don't mind my lazy self.
@ragingprodigy I will sort that out.
@shalvah I am using the getUrl function. Or maybe I didn't get you.
